app:
  image: php:7
  command: php -S 0.0.0.0:8000 /app/index.php
  env_file: .env
  ports:
    - "8000:8000"
  volumes:
    - ./app:/app

composer:
  restart: "no"
  image: composer
  command: install
  volumes:
    - ./app:/app
